version: '3.8'
services:
  db-postgres:
    container_name: hypertext-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=capstone
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: hypertext-redis
    image: redis:5.0.6
    ports:
      - "6379:6379"
  zookeeper:
    container_name: hypertext-zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
  kafka:
    container_name: hypertext-kafka
    image: 'bitnami/zookeeper:latest'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
